### ISSUE TITLE
Unrecognized command

### ISSUE THREAD

**Issue by mohamed-hmd** [dersia/AppStoreConnect#2]
Unrecognized command or argument '4xxxxxxa-1xx1-48xx-xxx-xxxxxxxxxxx'

**Comment by dersia** [comment]
I dont know what you are trying to do here.

**Comment by mohamed-hmd** [comment]
When using the command
appStoreConnect tools jwt fromFile create
~/private_keys/AuthKey_H439JXU4YA.p8 H439JXU4YA
1cc70e85-0db0-45bc-9a87-18e3e073ْ23hn6

I get this error :
Unrecognized command or argument '1cc70e85-0db0-45bc-9a87-18e3e073ْ23hn6'

**Comment by dersia** [comment]
The command is:
`appStoreConnect tools jwt create fromFile <PATH-TO-P8> <KID> <ISSUER ID>`

Make sure you use `create` before `fromFile`. And then you'll need the 
* P8 file: I guess in your case  `~/private_keys/AuthKey_H439JXU4YA.p8 H439JXU4YA`
* Your KID: I think this is missing
* Your Issuer Id: in your case `1cc70e85-0db0-45bc-9a87-18e3e073ْ23hn6`

Please try it like this again.

**Comment by mohamed-hmd** [comment]
how i create fromFile
im using your app to create one. (how i created formFile)

appStoreConnect tools jwt create fromFile <PATH-TO-P8> <KID> <ISSUER ID>

My KID: APPSTORE_CONNECT_API_KEY_ID=H439JXU4YA

**Comment by mohamed-hmd** [comment]
I am new to this type of too ٍso please help me and send me :

    * how i create fromFile (command or name and extension)

Please send me Your Paypal account because I want to support you because I
love supporting people who give free aid

**Comment by dersia** [comment]
Try this
`appStoreConnect tools jwt create fromFile ~/private_keys/AuthKey_H439JXU4YA.p8 H439JXU4YA 1cc70e85-0db0-45bc-9a87-18e3e073ْ23hn6`

If this doesn't work try using double quotes like this

`appStoreConnect tools jwt create fromFile "~/private_keys/AuthKey_H439JXU4YA.p8" "H439JXU4YA" "1cc70e85-0db0-45bc-9a87-18e3e073ْ23hn6"`

If this doesn't work either just reply here and I will see if I can reproduce it and fix it, if there is a bug.

**Comment by mohamed-hmd** [comment]
same problem
Unrecognized command or argument '1cc70e85-0db0-45bc-9a87-18e3e073cf9f'

**Comment by dersia** [comment]
Hey there

Sorry for the late reply.
Can you please check if your home directory has a space in it?

**Comment by dersia** [comment]
This is fixed in 0.3
